[package]
name = "task-master"
version = "0.1.0"
edition = "2024"

[dependencies]
fs = "0.0.5"
io = "0.0.2"
serde = "1.0.219"
serde_yaml = "0.9.34"
tokio = { version = "1.47.0", features = ["process", "macros", "rt-multi-thread"] }
