[programs.nginx]
cmd = "/usr/local/bin/nginx -c /etc/nginx/test.conf"
numprocs = 1
umask = 22
workingdir = "/tmp"
autostart = true
autorestart = "unexpected"
exitcodes = [0, 2]
startretries = 3
starttime = 5
stopsignal = "TERM"
stoptime = 10
stdout = "/tmp/nginx.stdout"
stderr = "/tmp/nginx.stderr"

[programs.nginx.env]
STARTED_BY = "taskmaster"
ANSWER = "42"

[programs.vogsphere]
cmd = "/usr/local/bin/vogsphere-worker --no-prefork"
numprocs = 8
umask = 77
workingdir = "/tmp"
autostart = true
autorestart = "unexpected"
exitcodes = [0]
startretries = 3
starttime = 5
stopsignal = "USR1"
stoptime = 10
stdout = "/tmp/vgsworker.stdout"
stderr = "/tmp/vgsworker.stderr"
